spring:
  profiles:
    active: dev
  datasource:
      url : jdbc:mysql://localhost:3306/springboot
      username : root
      password : root
#        driverClassName :
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      max-file-size: 128KB   #最大支持文件大小
      max-request-size: 128KB    #最大支持请求大小
#      file-size-threshold: 0  #支持文件写入磁盘
#      #默认支持文件上传
#      server.compression.enabled: true
#      server.compression.min-response-size: 1
#      server.connection-timeout: 5000





